import {
  Stethoscope, SmilePlus, Sparkles, Ribbon, HeartPulse, Scissors, Gem, ShieldCheck, Plane, Apple
} from "lucide-react";

export const treatments = [
  {
    slug: "prp-hair",
    label: "PRP/GFC for Hair",
    fullTitle: "PRP/GFC for Hair",
    icon: Sparkles,
    color: "#0E898F",
    bgColor: "#E6F4F4",
    image: "/images/treatments/cards/prp-hair.png",
    heroDesc: "Natural hair regrowth therapy using your own platelet-rich plasma for stronger, healthier hair growth.",
    features: [
      "Natural regrowth",
      "No side effects",
      "Strengthens follicles",
      "Minimally invasive",
      "Clinically proven",
      "Quick recovery",
    ],
    description: "PRP (Platelet-Rich Plasma) and GFC (Growth Factor Concentrate) are advanced, non-surgical treatments for hair loss. By using your own blood's growth factors, we stimulate hair follicles to promote natural regrowth and improve hair density.",
    stats: { doctors: 10, patients: "2K+", experience: "8 years" },
  },
  {
    slug: "facial-trauma",
    label: "Facial Trauma",
    fullTitle: "Advanced Emergency Care for Facial Injuries",
    icon: Stethoscope,
    color: "#0E898F",
    bgColor: "#E6F4F4",
    image: "/images/treatments/cards/facial-trauma.png",
    heroDesc: "Rapid emergency care, advanced surgical treatment, and aesthetic rehabilitation for facial injuries and maxillofacial trauma.",
    features: [
      "RTA Injury Management",
      "Jaw Fracture Fixation",
      "Facial Bone Reconstruction",
      "Soft Tissue Repair",
      "Orbital & Nasal Fractures",
      "Cosmetic Rehabilitation",
    ],
    description: "At MediNex+, we specialize in comprehensive management of facial trauma and maxillofacial injuries. Our approach combines precision surgical techniques and modular OT safety standards to restore function and confidence.",
    stats: { doctors: 12, patients: "12K+", experience: "15 years" },
  },
  {
    slug: "dental",
    label: "Dental",
    fullTitle: "Confident Smiles Begin with Expert Dental Care",
    icon: SmilePlus,
    color: "#10B981",
    bgColor: "#D1FAE5",
    image: "/images/treatments/cards/dental.png",
    heroDesc: "From routine checkups to advanced dental treatments, we provide painless, modern, and affordable solutions to keep your smile healthy and bright.",
    features: [
      "Teeth cleaning & polishing",
      "Root canal treatment",
      "Dental implants & crowns",
      "Orthodontics & braces",
      "Teeth whitening",
      "Wisdom tooth extraction",
    ],
    description: "Our dental department combines modern technology with expert care to give you a healthy, confident smile. From routine check-ups to advanced cosmetic procedures, our team of dental specialists ensures a comfortable experience with outstanding results.",
    stats: { doctors: 20, patients: "8K+", experience: "12 years" },
  },
  {
    slug: "dermatology",
    label: "Dermatology",
    fullTitle: "Healthy Skin, Confident You",
    icon: Sparkles,
    color: "#EC4899",
    bgColor: "#FCE7F3",
    image: "/images/treatments/cards/dermatology.png",
    heroDesc: "Treat acne, pigmentation, hair issues, and more with expert dermatologists. Personalized care for glowing, clear, and healthy skin.",
    features: [
      "Acne & scar treatment",
      "Laser therapy & skin resurfacing",
      "Hair loss treatment (PRP)",
      "Mole & skin tag removal",
      "Psoriasis & eczema management",
      "Anti-aging & cosmetic procedures",
    ],
    description: "Our dermatology department addresses a wide range of skin conditions using the latest diagnostic tools and treatments. Whether it's medical dermatology or cosmetic enhancements, our board-certified dermatologists deliver personalized, evidence-based care.",
    stats: { doctors: 15, patients: "6K+", experience: "10 years" },
  },
  {
    slug: "body-shaping",
    label: "Body Shaping",
    fullTitle: "Body Shaping & Contouring Center",
    icon: Scissors,
    color: "#10B981",
    bgColor: "#D1FAE5",
    image: "/images/treatments/cards/body-shaping.png",
    heroDesc: "Advanced non-surgical body contouring and fat reduction treatments for a toned and sculpted appearance.",
    features: [
      "Fat Reduction (Lipolysis)",
      "Cryolipolysis (Fat Freezing)",
      "Skin Tightening",
      "Cellulite Reduction",
      "Stretch Mark Treatments",
      "Transformation Programs",
    ],
    description: "At MediNex+, we offer advanced body contouring treatments using AI-based analysis and cutting-edge technologies to target stubborn fat and reshape your body safely.",
    stats: { doctors: 8, patients: "7K+", experience: "10 years" },
  },
  {
    slug: "premium-aesthetic",
    label: "Premium Aesthetic",
    fullTitle: "Premium Aesthetic & Cosmetic Center",
    icon: Gem,
    color: "#8B5CF6",
    bgColor: "#EDE9FE",
    image: "/images/treatments/cards/premium-aesthetic.png",
    heroDesc: "Luxury aesthetic care designed for natural, refined, and timeless beauty using advanced medical science.",
    features: [
      "Luxury Facial Aesthetics",
      "Non-Surgical Face Lift",
      "Jawline & Profile Enhancement",
      "Lip Augmentation",
      "Full Face Rejuvenation",
      "Bridal & Celebrity Makeovers",
    ],
    description: "Experience next-level aesthetic care where advanced medical science meets artistic precision. Our treatments enhance your natural features for elegant results.",
    stats: { doctors: 10, patients: "6K+", experience: "12 years" },
  },
  {
    slug: "sexual-health",
    label: "Sexual Health",
    fullTitle: "Sexual Health & Wellness (Men & Women)",
    icon: ShieldCheck,
    color: "#EF4444",
    bgColor: "#FEE2E2",
    image: "/images/treatments/cards/sexual-health.png",
    heroDesc: "Confidential, compassionate, and result-oriented care for intimate health using advanced medical and regenerative therapies.",
    features: [
      "Erectile Dysfunction Treatment",
      "Premature Ejaculation Mgmt",
      "Libido Enhancement",
      "Hormonal Therapy",
      "Female Sexual Wellness",
      "Couple Counseling",
    ],
    description: "Our specialized clinic offers confidential, ethical, and medically advanced treatments for both men and women, focusing on improving confidence and quality of life.",
    stats: { doctors: 6, patients: "5K+", experience: "12 years" },
  },
  {
    slug: "medical-tourism",
    label: "Medical Tourism",
    fullTitle: "Medical & Dental Tourism Center",
    icon: Plane,
    color: "#3B82F6",
    bgColor: "#DBEAFE",
    image: "/images/Quick-Treatments/Medicaltourism.png",
    heroDesc: "World-class healthcare in India with end-to-end support for international patients, including travel and luxury stay.",
    features: [
      "International Patient Services",
      "Customized Treatment Packages",
      "Visa & Travel Coordination",
      "Luxury Stay & Hospitality",
      "Virtual Consultations",
      "Cost-Effective Treatments",
    ],
    description: "MediNex+ offers a seamless medical tourism experience, combining advanced treatments with premium hospitality for international patients.",
    stats: { doctors: 15, patients: "Global", experience: "15 years" },
  },
  {
    slug: "nutrition",
    label: "Nutrition",
    fullTitle: "Clinical Nutrition & Metabolic Wellness",
    icon: Apple,
    color: "#F59E0B",
    bgColor: "#FEF3C7",
    image: "/images/Quick-Treatments/Nutrition.png",
    heroDesc: "Science-based nutrition and lifestyle care for sustainable weight management and metabolic health.",
    features: [
      "Personalized Diet Planning",
      "Weight Loss & Gain Programs",
      "PCOS & Thyroid Management",
      "Diabetic & Cardiac Nutrition",
      "Skin & Hair Nutrition",
      "Lifestyle Disease Reversal",
    ],
    description: "Our Clinical Nutrition programs combine clinical expertise with personalized diet planning to help you achieve long-term health transformation tailored to your medical needs.",
    stats: { doctors: 5, patients: "4K+", experience: "10 years" },
  },
  {
    slug: "cancer",
    label: "Cancer",
    fullTitle: "Compassionate Care. Advanced Cancer Treatment.",
    icon: Ribbon,
    color: "#8B5CF6",
    bgColor: "#EDE9FE",
    image: "/images/treatments/cards/cancer.png",
    heroDesc: "Early detection, expert oncologists, and personalized treatment plans — supporting you at every stage with care, strength, and hope.",
    features: [
      "Early cancer screening & detection",
      "Chemotherapy & immunotherapy",
      "Radiation therapy",
      "Surgical oncology",
      "Palliative & supportive care",
      "Genetic counseling & testing",
    ],
    description: "Our oncology center brings together a multidisciplinary team of cancer specialists to provide comprehensive treatment plans tailored to each patient. We combine the latest research, advanced technology, and compassionate care to fight cancer at every stage.",
    stats: { doctors: 30, patients: "5K+", experience: "14 years" },
  },
  {
    slug: "cardiology",
    label: "Cardiology",
    fullTitle: "Cardiology & Heart Care",
    icon: HeartPulse,
    color: "#EF4444",
    bgColor: "#FEE2E2",
    image: "/images/treatment-cardiology.png",
    heroDesc: "State-of-the-art cardiac diagnostics, interventions, and preventive care. Our cardiologists are leaders in treating complex cardiovascular conditions.",
    features: [
      "ECG, Echo & stress testing",
      "Cardiac catheterization & angioplasty",
      "Heart failure management",
      "Pacemaker & defibrillator implants",
      "Preventive cardiology programs",
      "Cardiac rehabilitation",
    ],
    description: "Our cardiology department is equipped with the most advanced diagnostic and interventional tools. From preventive heart health programs to complex cardiac surgeries, our experienced cardiologists are dedicated to keeping your heart strong and healthy.",
    stats: { doctors: 25, patients: "10K+", experience: "18 years" },
  },
];
