import nodemailer from "nodemailer";

export const sendLabReport = async (opts: {
  to: string;
  patientName: string;
  orderNo: string;
  hospitalName: string;
  doctorName?: string;
  reportDate: string;
  items: { testName: string; result: string; unit: string; normalRange: string; isAbnormal: boolean; isCritical: boolean }[];
}) => {
  const rowsHtml = opts.items.map(i => {
    const color = i.isCritical ? "#dc2626" : i.isAbnormal ? "#d97706" : "#059669";
    const flag = i.isCritical ? " 🚨 CRITICAL" : i.isAbnormal ? " ⚠ ABNORMAL" : "";
    return `<tr style="border-bottom:1px solid #f3f4f6;">
      <td style="padding:8px 12px;font-weight:600;color:#111;">${i.testName}</td>
      <td style="padding:8px 12px;font-weight:700;color:${color};">${i.result} ${i.unit}${flag}</td>
      <td style="padding:8px 12px;color:#6b7280;font-size:12px;">${i.normalRange || "—"}</td>
    </tr>`;
  }).join("");
  await transporter.sendMail({
    from: `"${opts.hospitalName} Lab" <${process.env.EMAIL_USERNAME || process.env.SMTP_USER}>`,
    to: opts.to,
    subject: `Lab Report ${opts.orderNo} – ${opts.hospitalName}`,
    html: `<table width="100%" cellpadding="0" cellspacing="0" style="font-family:sans-serif;max-width:600px;margin:0 auto;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden;">
<tr><td style="background:linear-gradient(135deg,#10b981,#047857);padding:20px 24px;color:#fff;">
  <div style="font-size:20px;font-weight:800;">🔬 Lab Report Ready</div>
  <div style="font-size:13px;opacity:.85;margin-top:4px;">${opts.hospitalName}</div>
</td></tr>
<tr><td style="padding:20px 24px;">
  <p style="font-size:14px;color:#374151;">Dear <strong>${opts.patientName}</strong>,</p>
  <p style="font-size:13px;color:#6b7280;">Your lab report <strong>${opts.orderNo}</strong> dated ${opts.reportDate} is ready. Please find your results below.</p>
  ${opts.doctorName ? `<p style="font-size:12px;color:#6b7280;">Ordered by: Dr. ${opts.doctorName}</p>` : ""}
  <table width="100%" style="border-collapse:collapse;margin:16px 0;border:1px solid #e5e7eb;border-radius:6px;overflow:hidden;">
    <thead><tr style="background:#f0fdf4;">
      <th style="padding:8px 12px;text-align:left;font-size:12px;color:#047857;">TEST</th>
      <th style="padding:8px 12px;text-align:left;font-size:12px;color:#047857;">RESULT</th>
      <th style="padding:8px 12px;text-align:left;font-size:12px;color:#047857;">NORMAL RANGE</th>
    </tr></thead>
    <tbody>${rowsHtml}</tbody>
  </table>
  <p style="font-size:11px;color:#9ca3af;margin-top:16px;">Please consult your doctor to discuss these results. This is a computer-generated report.</p>
</td></tr>
<tr><td style="padding:12px 24px;font-size:11px;color:#9ca3af;border-top:1px solid #f3f4f6;background:#f9fafb;">Auto-generated by ${opts.hospitalName} Lab. Do not reply to this email.</td></tr>
</table>`,
  });
};

const smtpUser = (process.env.EMAIL_USERNAME || process.env.SMTP_USER || "").trim();
const smtpPass = (process.env.EMAIL_PASSWORD || process.env.SMTP_PASS || "").replace(/\s/g, "");

console.log("[Mailer] Config:", {
  user: smtpUser ? `${smtpUser.slice(0, 4)}***${smtpUser.slice(-10)}` : "NOT SET",
  passLength: smtpPass.length,
});

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: { user: smtpUser, pass: smtpPass },
} as any);

transporter.verify().then(() => console.log("[Mailer] Gmail connected ✓")).catch((err) => console.error("[Mailer] Gmail FAILED:", err.message));

export const sendDoctorCredentials = async (opts: {
  to: string;
  name: string;
  email: string;
  password: string;
  hospitalName: string;
  loginUrl: string;
}) => {
  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Your Doctor Portal Credentials – ${opts.hospitalName}`,
    html: `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Doctor Portal Credentials</title>
</head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f9fafb;padding:40px 16px;">
    <tr>
      <td align="center">
        <table width="520" cellpadding="0" cellspacing="0" style="max-width:520px;width:100%;background:#ffffff;border-radius:12px;border:1px solid #e5e7eb;">
          <tr>
            <td style="padding:32px 40px 24px;border-bottom:1px solid #f3f4f6;">
              <p style="margin:0 0 4px;font-size:12px;font-weight:600;color:#9ca3af;text-transform:uppercase;letter-spacing:0.05em;">${opts.hospitalName}</p>
              <h1 style="margin:0;font-size:20px;font-weight:700;color:#111827;">Doctor Portal Access</h1>
            </td>
          </tr>
          <tr>
            <td style="padding:32px 40px;">
              <h2 style="margin:0 0 12px;font-size:16px;color:#111827;font-weight:600;">Welcome, Dr. ${opts.name}!</h2>
              <p style="margin:0 0 24px;font-size:14px;color:#4b5563;line-height:1.6;">
                Your doctor account has been successfully created. You can use the credentials below to log in to the hospital management system.
              </p>
              
              <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:20px;margin-bottom:28px;">
                <p style="margin:0 0 10px;font-size:13px;color:#6b7280;"><strong>Email Address:</strong> <span style="color:#111827;">${opts.email}</span></p>
                <p style="margin:0;font-size:13px;color:#6b7280;"><strong>Temporary Password:</strong> <code style="padding:4px 8px;background:#fff;border:1px solid #d1d5db;border-radius:4px;color:#111827;font-family:monospace;">${opts.password}</code></p>
              </div>

              <a href="${opts.loginUrl}" style="display:inline-block;background:#4f46e5;color:#fff;text-decoration:none;padding:12px 24px;border-radius:8px;font-size:14px;font-weight:600;">Sign in to Portal →</a>
              
              <p style="margin:24px 0 0;font-size:13px;color:#9ca3af;line-height:1.5;">
                For your security, please change your password as soon as you log in for the first time.
              </p>
            </td>
          </tr>
          <tr>
            <td style="padding:16px 40px 24px;border-top:1px solid #f3f4f6;text-align:center;">
              <p style="margin:0;font-size:12px;color:#d1d5db;">© ${new Date().getFullYear()} ${opts.hospitalName} · Automated message</p>
            </td>
          </tr>
        </table>
      </td>
    </tr>
  </table>
</body>
</html>
    `,
  });
};

export const sendPatientWelcome = async (opts: {
  to: string;
  name: string;
  patientId: string;
  hospitalName: string;
  hospitalLogo?: string | null;
  appointmentInfo?: { date: string; doctor: string; timeSlot: string } | null;
}) => {
  const logoHtml = opts.hospitalLogo
    ? `<img src="${opts.hospitalLogo}" alt="${opts.hospitalName}" style="max-height:100px;max-width:280px;object-fit:contain;" />`
    : `<span style="font-size:48px;">🏥</span>`;

  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Welcome to ${opts.hospitalName} – Your Patient ID`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:480px;margin:0 auto;background:#fff;border:1px solid #f1f5f9;border-radius:12px;overflow:hidden;">
        <div style="padding:24px;text-align:center;border-bottom:1px solid #f1f5f9;">
          ${logoHtml}
        </div>
        <div style="padding:24px;">
          <h2 style="color:#334155;font-size:16px;margin:0 0 6px;font-weight:600;">Welcome, ${opts.name}!</h2>
          <p style="color:#64748b;font-size:12px;line-height:1.5;margin:0 0 16px;">You have been successfully registered. Please keep your Patient ID safe for all future visits.</p>
          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:16px 0;text-align:center;">
            <div style="font-size:11px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px;">Your Patient ID</div>
            <div style="font-size:22px;font-weight:700;color:#0f172a;font-family:monospace;letter-spacing:.05em;">${opts.patientId}</div>
          </div>
          ${
            opts.appointmentInfo
              ? `<div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin-bottom:16px;">
            <div style="font-size:11px;font-weight:600;color:#64748b;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px;">Your Appointment</div>
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;width:80px;">Doctor</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.appointmentInfo.doctor}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;">Date</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.appointmentInfo.date}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;">Time</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.appointmentInfo.timeSlot}</td></tr>
            </table>
          </div>`
              : ""
          }
          <p style="color:#94a3b8;font-size:11px;margin-top:16px;line-height:1.4;">Please arrive 15 minutes early. Bring this Patient ID to the reception desk. Contact us 24 hours in advance for rescheduling.</p>
        </div>
      </div>
    `,
  });
};

export const sendAppointmentConfirmation = async (opts: {
  to: string;
  patientName: string;
  patientId: string;
  doctorName: string;
  departmentName: string;
  appointmentDate: string;
  timeSlot: string;
  tokenNumber?: number | null;
  type: string;
  hospitalName: string;
  hospitalLogo?: string | null;
}) => {
  const logoHtml = opts.hospitalLogo
    ? `<img src="${opts.hospitalLogo}" alt="${opts.hospitalName}" style="max-height:100px;max-width:280px;object-fit:contain;" />`
    : `<span style="font-size:48px;">🏥</span>`;

  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Appointment Confirmed – ${opts.hospitalName}`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:480px;margin:0 auto;background:#fff;border:1px solid #f1f5f9;border-radius:12px;overflow:hidden;">
        <div style="padding:24px;text-align:center;border-bottom:1px solid #f1f5f9;">
          ${logoHtml}
        </div>
        <div style="padding:24px;">
          <h2 style="color:#334155;font-size:16px;margin:0 0 6px;font-weight:600;">Hi, ${opts.patientName}!</h2>
          <p style="color:#64748b;font-size:12px;line-height:1.5;margin:0 0 16px;">Your appointment has been confirmed. Here are the details:</p>
          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:16px 0;">
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;width:100px;">Patient ID</td><td style="font-size:12px;color:#334155;font-family:monospace;font-weight:600;">${opts.patientId}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Doctor</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.doctorName}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Department</td><td style="font-size:12px;color:#334155;">${opts.departmentName}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Date</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.appointmentDate}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Time</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.timeSlot}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Type</td><td style="font-size:12px;color:#334155;">${opts.type}</td></tr>
              ${opts.tokenNumber ? `<tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Token No.</td><td style="font-size:18px;font-weight:700;color:#0e898f;">#${opts.tokenNumber}</td></tr>` : ""}
            </table>
          </div>
          <p style="color:#94a3b8;font-size:11px;margin-top:16px;line-height:1.4;">Please arrive 15 minutes before your scheduled time. Carry a valid photo ID and previous medical records if available.</p>
        </div>
      </div>
    `,
  });
};

export const sendDeptCredentials = async (opts: {
  to: string;
  name: string;
  email: string;
  password: string;
  deptName: string;
  deptType: string;
  hospitalName: string;
  loginUrl: string;
}) => {
  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Your Department Head Portal Credentials – ${opts.hospitalName}`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#0E898F,#07595D);padding:32px 24px;text-align:center;">
          <h1 style="color:#fff;font-size:22px;margin:0;">🏥 ${opts.hospitalName}</h1>
          <p style="color:#B3E0E0;margin:8px 0 0;font-size:14px;">${opts.deptName} — Department Head Portal</p>
        </div>
        <div style="padding:32px 24px;">
          <h2 style="color:#1e293b;font-size:18px;margin:0 0 8px;">Welcome, ${opts.name}!</h2>
          <p style="color:#64748b;font-size:14px;line-height:1.6;">Your <strong>${opts.deptName}</strong> department head portal access has been created. Use the credentials below to log in and manage your department and all its sub-departments.</p>
          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:20px;margin:24px 0;">
            <table style="width:100%;border-collapse:collapse;">
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;width:120px;">Email</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;">${opts.email}</td>
              </tr>
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;">Password</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;font-family:monospace;background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:4px 10px;">${opts.password}</td>
              </tr>
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;">Department</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;">${opts.deptName} (${opts.deptType})</td>
              </tr>
            </table>
          </div>
          <a href="${opts.loginUrl}" style="display:inline-block;background:linear-gradient(135deg,#0E898F,#07595D);color:#fff;text-decoration:none;padding:12px 28px;border-radius:9px;font-size:14px;font-weight:700;">Login to Department Portal →</a>
          <p style="color:#94a3b8;font-size:12px;margin-top:24px;">For security, please change your password after your first login. If you didn't expect this email, contact your hospital administrator.</p>
        </div>
      </div>
    `,
  });
};

export const sendSubDeptCredentials = async (opts: {
  to: string;
  name: string;
  email: string;
  password: string;
  deptName: string;
  deptType: string;
  hospitalName: string;
  loginUrl: string;
}) => {
  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Your ${opts.deptName} Portal Credentials – ${opts.hospitalName}`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#6366f1,#4f46e5);padding:32px 24px;text-align:center;">
          <h1 style="color:#fff;font-size:22px;margin:0;">🏥 ${opts.hospitalName}</h1>
          <p style="color:#c7d2fe;margin:8px 0 0;font-size:14px;">${opts.deptName} — Sub-Department Portal</p>
        </div>
        <div style="padding:32px 24px;">
          <h2 style="color:#1e293b;font-size:18px;margin:0 0 8px;">Welcome, ${opts.name}!</h2>
          <p style="color:#64748b;font-size:14px;line-height:1.6;">Your <strong>${opts.deptName}</strong> portal access has been created. Use the credentials below to log in.</p>
          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:20px;margin:24px 0;">
            <table style="width:100%;border-collapse:collapse;">
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;width:120px;">Email</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;">${opts.email}</td>
              </tr>
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;">Password</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;font-family:monospace;background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:4px 10px;">${opts.password}</td>
              </tr>
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;">Department</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;">${opts.deptName} (${opts.deptType})</td>
              </tr>
            </table>
          </div>
          <a href="${opts.loginUrl}" style="display:inline-block;background:linear-gradient(135deg,#6366f1,#4f46e5);color:#fff;text-decoration:none;padding:12px 28px;border-radius:9px;font-size:14px;font-weight:700;">Login to Department Portal →</a>
          <p style="color:#94a3b8;font-size:12px;margin-top:24px;">For security, please change your password after your first login. If you didn't expect this email, contact your hospital administrator.</p>
        </div>
      </div>
    `,
  });
};

export const sendPrescriptionEmail = async (opts: {
  to: string;
  patientName: string;
  prescriptionNo: string;
  doctorName: string;
  doctorSpecialization: string;
  departmentName: string;
  diagnosis: string;
  medications: string;
  labTests: string;
  advice: string;
  followUpDate: string | null;
  hospitalName: string;
  date: string;
}) => {
  let medsHtml = "";
  try {
    const meds = JSON.parse(opts.medications);
    if (meds.length > 0) {
      medsHtml = `<table style="width:100%;border-collapse:collapse;margin:16px 0;">
        <tr style="background:#f8fafc;"><th style="text-align:left;padding:8px 10px;font-size:12px;color:#64748b;border-bottom:2px solid #e2e8f0;">Medication</th><th style="text-align:left;padding:8px 10px;font-size:12px;color:#64748b;border-bottom:2px solid #e2e8f0;">Dosage</th><th style="text-align:left;padding:8px 10px;font-size:12px;color:#64748b;border-bottom:2px solid #e2e8f0;">Frequency</th><th style="text-align:left;padding:8px 10px;font-size:12px;color:#64748b;border-bottom:2px solid #e2e8f0;">Duration</th><th style="text-align:left;padding:8px 10px;font-size:12px;color:#64748b;border-bottom:2px solid #e2e8f0;">Instructions</th></tr>
        ${meds.map((m: any) => `<tr><td style="padding:8px 10px;font-size:13px;color:#1e293b;border-bottom:1px solid #f1f5f9;font-weight:600;">${m.name}</td><td style="padding:8px 10px;font-size:13px;color:#475569;border-bottom:1px solid #f1f5f9;">${m.dosage}</td><td style="padding:8px 10px;font-size:13px;color:#475569;border-bottom:1px solid #f1f5f9;">${m.frequency}</td><td style="padding:8px 10px;font-size:13px;color:#475569;border-bottom:1px solid #f1f5f9;">${m.duration}</td><td style="padding:8px 10px;font-size:13px;color:#475569;border-bottom:1px solid #f1f5f9;">${m.instructions || "—"}</td></tr>`).join("")}
      </table>`;
    }
  } catch {}

  let testsHtml = "";
  try {
    const tests = JSON.parse(opts.labTests);
    if (tests.length > 0) {
      testsHtml = `<div style="margin:16px 0;"><p style="font-size:13px;font-weight:700;color:#1e293b;margin:0 0 8px;">Lab Tests Recommended:</p><ul style="margin:0;padding-left:20px;">${tests.map((t: any) => `<li style="font-size:13px;color:#475569;margin-bottom:4px;">${t.name} <span style="color:#94a3b8;">(${t.urgency})</span></li>`).join("")}</ul></div>`;
    }
  } catch {}

  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Your Prescription ${opts.prescriptionNo} – ${opts.hospitalName}`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:650px;margin:0 auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#0ea5e9,#0369a1);padding:32px 24px;text-align:center;">
          <h1 style="color:#fff;font-size:22px;margin:0;">🏥 ${opts.hospitalName}</h1>
          <p style="color:#bae6fd;margin:8px 0 0;font-size:14px;">Digital Prescription</p>
        </div>
        <div style="padding:32px 24px;">
          <div style="display:flex;justify-content:space-between;margin-bottom:24px;">
            <div>
              <p style="margin:0;font-size:12px;color:#94a3b8;font-weight:600;">PRESCRIPTION NO</p>
              <p style="margin:4px 0 0;font-size:18px;font-weight:800;color:#0c4a6e;font-family:monospace;">${opts.prescriptionNo}</p>
            </div>
            <div style="text-align:right;">
              <p style="margin:0;font-size:12px;color:#94a3b8;">Date: ${opts.date}</p>
            </div>
          </div>
          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:16px;margin-bottom:20px;">
            <p style="margin:0 0 4px;font-size:12px;color:#94a3b8;font-weight:600;">PATIENT</p>
            <p style="margin:0;font-size:16px;font-weight:700;color:#1e293b;">${opts.patientName}</p>
          </div>
          <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:10px;padding:16px;margin-bottom:20px;">
            <p style="margin:0 0 4px;font-size:12px;color:#059669;font-weight:600;">CONSULTING DOCTOR</p>
            <p style="margin:0;font-size:15px;font-weight:700;color:#1e293b;">Dr. ${opts.doctorName}</p>
            <p style="margin:4px 0 0;font-size:12px;color:#64748b;">${opts.doctorSpecialization} · ${opts.departmentName}</p>
          </div>
          ${opts.diagnosis ? `<div style="margin-bottom:16px;"><p style="font-size:13px;font-weight:700;color:#1e293b;margin:0 0 4px;">Diagnosis:</p><p style="font-size:13px;color:#475569;margin:0;">${opts.diagnosis}</p></div>` : ""}
          ${medsHtml ? `<div style="margin-bottom:16px;"><p style="font-size:13px;font-weight:700;color:#1e293b;margin:0 0 4px;">Medications:</p>${medsHtml}</div>` : ""}
          ${testsHtml}
          ${opts.advice ? `<div style="margin-bottom:16px;"><p style="font-size:13px;font-weight:700;color:#1e293b;margin:0 0 4px;">Advice:</p><p style="font-size:13px;color:#475569;margin:0;white-space:pre-line;">${opts.advice}</p></div>` : ""}
          ${opts.followUpDate ? `<div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:12px;margin-top:16px;"><p style="margin:0;font-size:13px;color:#92400e;font-weight:600;">📅 Follow-up Date: ${opts.followUpDate}</p></div>` : ""}
          <p style="color:#94a3b8;font-size:11px;margin-top:24px;border-top:1px solid #e2e8f0;padding-top:16px;">This is a digitally generated prescription from ${opts.hospitalName}. Please consult your doctor before making any changes to the prescribed medications.</p>
        </div>
      </div>
    `,
  });
};

export const sendFinanceCredentials = async (
  to: string,
  name: string,
  password: string,
  hospitalName: string
) => {
  await transporter.sendMail({
    from: `"${hospitalName}" <${smtpUser}>`,
    to,
    subject: `Your Finance Department Credentials – ${hospitalName}`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#f59e0b,#b45309);padding:32px 24px;text-align:center;">
          <h1 style="color:#fff;font-size:22px;margin:0;">🏥 ${hospitalName}</h1>
          <p style="color:#fef3c7;margin:8px 0 0;font-size:14px;">Finance Department Portal Access</p>
        </div>
        <div style="padding:32px 24px;">
          <h2 style="color:#1e293b;font-size:18px;margin:0 0 8px;">Welcome, ${name}!</h2>
          <p style="color:#64748b;font-size:14px;line-height:1.6;">Your Finance Department head account has been created. Use the credentials below to access the Finance Portal.</p>
          <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:10px;padding:20px;margin:24px 0;">
            <p style="margin:0 0 10px;font-size:13px;color:#78350f;"><strong>Login Email:</strong> <span style="color:#1e293b;">${to}</span></p>
            <p style="margin:0;font-size:13px;color:#78350f;"><strong>Password:</strong> <code style="padding:4px 10px;background:#fff;border:1px solid #fde68a;border-radius:6px;color:#1e293b;font-family:monospace;">${password}</code></p>
          </div>
          <p style="color:#94a3b8;font-size:12px;margin-top:24px;">Please change your password after your first login. If you didn't expect this email, contact your hospital administrator.</p>
        </div>
      </div>
    `,
  });
};

export const sendAppointmentReminder = async (opts: {
  to: string;
  patientName: string;
  patientId: string;
  doctorName: string;
  departmentName: string;
  appointmentDate: string;
  timeSlot: string;
  tokenNumber?: number | null;
  type: string;
  hospitalName: string;
  hospitalLogo?: string | null;
}) => {
  const logoHtml = opts.hospitalLogo
    ? `<img src="${opts.hospitalLogo}" alt="${opts.hospitalName}" style="max-height:100px;max-width:280px;object-fit:contain;" />`
    : `<span style="font-size:48px;">🏥</span>`;

  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Appointment Reminder – ${opts.hospitalName}`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:480px;margin:0 auto;background:#fff;border:1px solid #f1f5f9;border-radius:12px;overflow:hidden;">
        <div style="padding:24px;text-align:center;border-bottom:1px solid #f1f5f9;">
          ${logoHtml}
        </div>
        <div style="padding:24px;">
          <h2 style="color:#334155;font-size:16px;margin:0 0 6px;font-weight:600;">Hi, ${opts.patientName}!</h2>
          <p style="color:#64748b;font-size:12px;line-height:1.5;margin:0 0 16px;">This is a friendly reminder about your upcoming appointment:</p>
          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:16px 0;">
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;width:100px;">Patient ID</td><td style="font-size:12px;color:#334155;font-family:monospace;font-weight:600;">${opts.patientId}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Doctor</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.doctorName}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Department</td><td style="font-size:12px;color:#334155;">${opts.departmentName}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Date</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.appointmentDate}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Time</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.timeSlot}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Type</td><td style="font-size:12px;color:#334155;">${opts.type}</td></tr>
              ${opts.tokenNumber ? `<tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Token No.</td><td style="font-size:18px;font-weight:700;color:#0e898f;">#${opts.tokenNumber}</td></tr>` : ""}
            </table>
          </div>
          <p style="color:#94a3b8;font-size:11px;margin-top:16px;line-height:1.4;">Please arrive 15 minutes before your scheduled time. Carry a valid photo ID and any previous medical records.</p>
        </div>
      </div>
    `,
  });
};

export const sendStaffCredentials = async (opts: {
  to: string;
  name: string;
  email: string;
  password: string;
  role: string;
  hospitalName: string;
  loginUrl: string;
}) => {
  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Your Staff Portal Credentials – ${opts.hospitalName}`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:600px;margin:0 auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;overflow:hidden;">
        <div style="background:linear-gradient(135deg,#10b981,#059669);padding:32px 24px;text-align:center;">
          <h1 style="color:#fff;font-size:22px;margin:0;">🏥 ${opts.hospitalName}</h1>
          <p style="color:#d1fae5;margin:8px 0 0;font-size:14px;">Staff Portal Access</p>
        </div>
        <div style="padding:32px 24px;">
          <h2 style="color:#1e293b;font-size:18px;margin:0 0 8px;">Welcome, ${opts.name}!</h2>
          <p style="color:#64748b;font-size:14px;line-height:1.6;">Your staff account has been created with the role of <strong>${opts.role}</strong>. Use the credentials below to access your portal.</p>
          <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;padding:20px;margin:24px 0;">
            <table style="width:100%;border-collapse:collapse;">
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;width:120px;">Email</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;">${opts.email}</td>
              </tr>
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;">Password</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;font-family:monospace;background:#fff;border:1px solid #e2e8f0;border-radius:6px;padding:4px 10px;">${opts.password}</td>
              </tr>
              <tr>
                <td style="font-size:13px;color:#64748b;padding:8px 0;font-weight:600;">Role</td>
                <td style="font-size:13px;color:#1e293b;padding:8px 0;">${opts.role}</td>
              </tr>
            </table>
          </div>
          <a href="${opts.loginUrl}" style="display:inline-block;background:linear-gradient(135deg,#10b981,#059669);color:#fff;text-decoration:none;padding:12px 28px;border-radius:9px;font-size:14px;font-weight:700;">Login to Portal →</a>
          <p style="color:#94a3b8;font-size:12px;margin-top:24px;"><strong>Important:</strong> You must change your password after your first login. If you didn't expect this email, contact your hospital administrator immediately.</p>
        </div>
      </div>
    `,
  });
};

export const sendEnquiryConfirmation = async (opts: {
  to: string;
  fullName: string;
  mobile: string;
  department: string;
  enquiryType: string;
  details: string;
  hospitalName: string;
  hospitalEmail: string;
  hospitalPhone: string;
  hospitalLogo?: string | null;
}) => {
  const logoHtml = opts.hospitalLogo
    ? `<img src="${opts.hospitalLogo}" alt="${opts.hospitalName}" style="max-height:60px;max-width:200px;object-fit:contain;margin-bottom:12px;" />`
    : `<div style="font-size:18px;font-weight:700;color:#334155;margin-bottom:12px;">${opts.hospitalName}</div>`;

  console.log("[Mailer] sendEnquiryConfirmation - Sending to:", opts.to);
  
  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Enquiry Received – ${opts.hospitalName}`,
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;max-width:560px;margin:40px auto;background:#ffffff;border:1px solid #f1f5f9;border-radius:8px;overflow:hidden;">
        <div style="padding:32px 32px 24px;text-align:center;border-bottom:1px solid #f8fafc;">
          ${logoHtml}
          <div style="font-size:13px;color:#94a3b8;font-weight:500;">Enquiry Confirmation</div>
        </div>
        
        <div style="padding:28px 32px;">
          <p style="font-size:15px;color:#1e293b;margin:0 0 8px;font-weight:600;">Hello ${opts.fullName},</p>
          <p style="font-size:14px;color:#64748b;line-height:1.6;margin:0 0 24px;">Thank you for reaching out to us. We have received your enquiry and our team will get back to you shortly.</p>
          
          <div style="background:#fafbfc;border:1px solid #f1f5f9;border-radius:6px;padding:18px;margin-bottom:20px;">
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="font-size:13px;color:#94a3b8;padding:5px 0;width:100px;">Name</td><td style="font-size:13px;color:#334155;padding:5px 0;">${opts.fullName}</td></tr>
              <tr><td style="font-size:13px;color:#94a3b8;padding:5px 0;">Mobile</td><td style="font-size:13px;color:#334155;padding:5px 0;">${opts.mobile}</td></tr>
              ${opts.department ? `<tr><td style="font-size:13px;color:#94a3b8;padding:5px 0;">Department</td><td style="font-size:13px;color:#334155;padding:5px 0;">${opts.department}</td></tr>` : ""}
              ${opts.enquiryType ? `<tr><td style="font-size:13px;color:#94a3b8;padding:5px 0;">Type</td><td style="font-size:13px;color:#334155;padding:5px 0;">${opts.enquiryType}</td></tr>` : ""}
            </table>
          </div>
          
          ${opts.details ? `
          <div style="background:#fefefe;border:1px solid #f1f5f9;border-radius:6px;padding:14px;margin-bottom:20px;">
            <div style="font-size:11px;color:#94a3b8;margin-bottom:6px;text-transform:uppercase;letter-spacing:0.5px;">Your Message</div>
            <div style="font-size:13px;color:#475569;line-height:1.6;white-space:pre-wrap;">${opts.details}</div>
          </div>` : ""}
          
          <div style="font-size:13px;color:#64748b;line-height:1.6;margin-bottom:6px;">For urgent queries, please contact us:</div>
          <div style="font-size:13px;color:#334155;line-height:1.7;">
            <div>📞 <a href="tel:${opts.hospitalPhone}" style="color:#0E898F;text-decoration:none;">${opts.hospitalPhone}</a></div>
            <div>✉️ <a href="mailto:${opts.hospitalEmail}" style="color:#0E898F;text-decoration:none;">${opts.hospitalEmail}</a></div>
          </div>
        </div>
        
        <div style="padding:16px 32px;background:#fafbfc;border-top:1px solid #f1f5f9;text-align:center;">
          <p style="margin:0;font-size:11px;color:#cbd5e1;">This is an automated message from ${opts.hospitalName}</p>
        </div>
      </div>
    `,
  });
};

export const sendEnquiryNotificationToHospital = async (opts: {
  to: string;
  fullName: string;
  mobile: string;
  altContact: string;
  email: string;
  gender: string;
  city: string;
  state: string;
  country: string;
  pincode: string;
  department: string;
  enquiryType: string;
  details: string;
  hospitalName: string;
  hospitalLogo?: string | null;
  enquiryId: string;
}) => {
  const logoHtml = opts.hospitalLogo
    ? `<img src="${opts.hospitalLogo}" alt="${opts.hospitalName}" style="max-height:50px;max-width:180px;object-fit:contain;margin-bottom:10px;" />`
    : `<div style="font-size:16px;font-weight:700;color:#334155;margin-bottom:10px;">${opts.hospitalName}</div>`;

  console.log("[Mailer] sendEnquiryNotificationToHospital - Sending to:", opts.to);
  
  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `New Enquiry from ${opts.fullName} – ${opts.department || "General"}`,
    html: `
      <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,sans-serif;max-width:600px;margin:40px auto;background:#ffffff;border:1px solid #f1f5f9;border-radius:8px;overflow:hidden;">
        <div style="padding:24px 28px;text-align:center;background:#fafbfc;border-bottom:1px solid #f1f5f9;">
          ${logoHtml}
          <div style="font-size:15px;color:#334155;font-weight:600;margin-bottom:2px;">New Enquiry Received</div>
          <div style="font-size:11px;color:#cbd5e1;font-family:monospace;">ID: ${opts.enquiryId}</div>
        </div>
        
        <div style="padding:24px 28px;">
          <div style="background:#fafbfc;border:1px solid #f1f5f9;border-radius:6px;padding:16px;margin-bottom:14px;">
            <div style="font-size:12px;color:#94a3b8;margin-bottom:10px;font-weight:600;">Contact Details</div>
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="font-size:13px;color:#94a3b8;padding:4px 0;width:100px;">Name</td><td style="font-size:13px;color:#334155;padding:4px 0;font-weight:600;">${opts.fullName}</td></tr>
              <tr><td style="font-size:13px;color:#94a3b8;padding:4px 0;">Mobile</td><td style="font-size:13px;color:#334155;padding:4px 0;"><a href="tel:${opts.mobile}" style="color:#0E898F;text-decoration:none;">${opts.mobile}</a></td></tr>
              ${opts.altContact ? `<tr><td style="font-size:13px;color:#94a3b8;padding:4px 0;">Alt Contact</td><td style="font-size:13px;color:#334155;padding:4px 0;">${opts.altContact}</td></tr>` : ""}
              ${opts.email ? `<tr><td style="font-size:13px;color:#94a3b8;padding:4px 0;">Email</td><td style="font-size:13px;color:#334155;padding:4px 0;"><a href="mailto:${opts.email}" style="color:#0E898F;text-decoration:none;">${opts.email}</a></td></tr>` : ""}
              ${opts.gender ? `<tr><td style="font-size:13px;color:#94a3b8;padding:4px 0;">Gender</td><td style="font-size:13px;color:#334155;padding:4px 0;">${opts.gender}</td></tr>` : ""}
            </table>
          </div>
          
          <div style="background:#fafbfc;border:1px solid #f1f5f9;border-radius:6px;padding:16px;margin-bottom:14px;">
            <div style="font-size:12px;color:#94a3b8;margin-bottom:8px;font-weight:600;">Location</div>
            <div style="font-size:13px;color:#475569;">
              ${[opts.city, opts.state, opts.country].filter(Boolean).join(", ") || "Not provided"}
              ${opts.pincode ? ` – ${opts.pincode}` : ""}
            </div>
          </div>
          
          <div style="background:#fafbfc;border:1px solid #f1f5f9;border-radius:6px;padding:16px;margin-bottom:14px;">
            <div style="font-size:12px;color:#94a3b8;margin-bottom:10px;font-weight:600;">Enquiry Details</div>
            <table style="width:100%;border-collapse:collapse;">
              ${opts.department ? `<tr><td style="font-size:13px;color:#94a3b8;padding:4px 0;width:100px;">Department</td><td style="font-size:13px;color:#334155;padding:4px 0;font-weight:600;">${opts.department}</td></tr>` : ""}
              ${opts.enquiryType ? `<tr><td style="font-size:13px;color:#94a3b8;padding:4px 0;">Type</td><td style="font-size:13px;color:#334155;padding:4px 0;">${opts.enquiryType}</td></tr>` : ""}
            </table>
          </div>
          
          ${opts.details ? `
          <div style="background:#fefefe;border:1px solid #f1f5f9;border-radius:6px;padding:14px;margin-bottom:14px;">
            <div style="font-size:11px;color:#94a3b8;margin-bottom:6px;text-transform:uppercase;letter-spacing:0.5px;">Message</div>
            <div style="font-size:13px;color:#475569;line-height:1.6;white-space:pre-wrap;">${opts.details}</div>
          </div>` : ""}
          
          <div style="font-size:11px;color:#cbd5e1;padding-top:12px;border-top:1px solid #f8fafc;">
            Submitted at ${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}
          </div>
        </div>
      </div>
    `,
  });
};

export const sendPayslipEmail = async (opts: {
  to: string;
  staffName: string;
  month: string;
  netPay: number;
  hospitalName: string;
  hospitalLogo?: string | null;
}) => {
  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Salary Slip for ${opts.month} – ${opts.hospitalName}`,
    html: `
<!DOCTYPE html><html><head><meta charset="UTF-8"/></head>
<body style="margin:0;padding:0;background:#f9fafb;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f9fafb;padding:40px 16px;"><tr><td align="center">
<table width="520" cellpadding="0" cellspacing="0" style="max-width:520px;width:100%;background:#fff;border-radius:12px;border:1px solid #e5e7eb;">
<tr><td style="padding:28px 36px;border-bottom:1px solid #f3f4f6;">
  ${opts.hospitalLogo ? `<img src="${opts.hospitalLogo}" alt="${opts.hospitalName}" style="max-height:40px;margin-bottom:12px;" />` : ""}
  <h2 style="margin:0;font-size:18px;color:#0E898F;">${opts.hospitalName}</h2>
</td></tr>
<tr><td style="padding:28px 36px;">
  <p style="margin:0 0 16px;font-size:15px;color:#1e293b;">Dear <strong>${opts.staffName}</strong>,</p>
  <p style="margin:0 0 16px;font-size:14px;color:#475569;line-height:1.6;">Your salary slip for <strong>${opts.month}</strong> has been generated.</p>
  <div style="background:#E6F4F4;border-radius:10px;padding:16px 20px;margin-bottom:16px;border:1px solid #B3E0E0;">
    <div style="font-size:12px;color:#0A6B70;font-weight:600;margin-bottom:4px;">Net Pay</div>
    <div style="font-size:24px;font-weight:800;color:#0E898F;">₹${opts.netPay.toLocaleString("en-IN")}</div>
  </div>
  <p style="margin:0;font-size:13px;color:#94a3b8;">Please contact HR for any queries regarding your payslip.</p>
</td></tr>
<tr><td style="padding:16px 36px;border-top:1px solid #f3f4f6;font-size:11px;color:#94a3b8;">
  This is a computer-generated email and does not require authentication.
</td></tr>
</table></td></tr></table></body></html>`,
  });
};

export const sendAppointmentRescheduled = async (opts: {
  to: string;
  patientName: string;
  patientId: string;
  doctorName: string;
  departmentName: string;
  oldDate: string;
  oldTimeSlot: string;
  newDate: string;
  newTimeSlot: string;
  tokenNumber?: number | null;
  type: string;
  hospitalName: string;
  hospitalLogo?: string | null;
}) => {
  const logoHtml = opts.hospitalLogo
    ? `<img src="${opts.hospitalLogo}" alt="${opts.hospitalName}" style="max-height:100px;max-width:280px;object-fit:contain;" />`
    : `<div style="font-size:18px;font-weight:700;color:#0f172a;">${opts.hospitalName}</div>`;

  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Appointment Rescheduled – ${opts.hospitalName}`,
    html: `
      <div style="font-family:'Inter',Arial,sans-serif;max-width:480px;margin:0 auto;background:#fff;border:1px solid #f1f5f9;border-radius:12px;overflow:hidden;">
        <div style="padding:24px;text-align:center;border-bottom:1px solid #f1f5f9;">
          ${logoHtml}
          <div style="font-size:13px;color:#64748b;margin-top:8px;">Appointment Update</div>
        </div>
        <div style="padding:24px;">
          <h2 style="color:#334155;font-size:16px;margin:0 0 6px;font-weight:600;">Hi, ${opts.patientName}!</h2>
          <p style="color:#64748b;font-size:12px;line-height:1.5;margin:0 0 16px;">Your appointment has been <strong style="color:#d97706;">rescheduled</strong> by the doctor. Please find your updated details below:</p>

          <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:8px;padding:12px;margin-bottom:16px;">
            <div style="font-size:11px;font-weight:600;color:#92400e;text-transform:uppercase;letter-spacing:.05em;margin-bottom:6px;">Previous Slot</div>
            <div style="font-size:13px;color:#b45309;font-weight:500;text-decoration:line-through;">${opts.oldDate} at ${opts.oldTimeSlot}</div>
          </div>

          <div style="background:#f0fdf4;border:1px solid #bbf7d0;border-radius:8px;padding:16px;margin-bottom:16px;">
            <div style="font-size:11px;font-weight:600;color:#166534;text-transform:uppercase;letter-spacing:.05em;margin-bottom:10px;">Updated Appointment</div>
            <table style="width:100%;border-collapse:collapse;">
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;width:100px;">Patient ID</td><td style="font-size:12px;color:#334155;font-family:monospace;font-weight:600;">${opts.patientId}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Doctor</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.doctorName}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Department</td><td style="font-size:12px;color:#334155;">${opts.departmentName}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Date</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.newDate}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Time</td><td style="font-size:12px;color:#334155;font-weight:500;">${opts.newTimeSlot}</td></tr>
              <tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Type</td><td style="font-size:12px;color:#334155;">${opts.type}</td></tr>
              ${opts.tokenNumber ? `<tr><td style="font-size:12px;color:#64748b;padding:4px 0;font-weight:500;">Token No.</td><td style="font-size:18px;font-weight:700;color:#0e898f;">#${opts.tokenNumber}</td></tr>` : ""}
            </table>
          </div>

          <p style="color:#94a3b8;font-size:11px;margin:0;">If you have any questions, please contact the hospital reception.</p>
        </div>
        <div style="padding:16px 24px;background:#f8fafc;border-top:1px solid #f1f5f9;font-size:11px;color:#94a3b8;text-align:center;">
          This is an automated notification from ${opts.hospitalName}.
        </div>
      </div>
    `,
  });
};

export const sendBillInvoice = async (opts: {
  to: string;
  patientName: string;
  patientId: string;
  billNo: string;
  billDate: string;
  total: number;
  paidAmount: number;
  status: string;
  hospitalName: string;
  hospitalLogo?: string | null;
  pdfBuffer: Buffer;
}) => {
  const isPaid = opts.status === "PAID";
  const headerContent = opts.hospitalLogo
    ? `<img src="${opts.hospitalLogo}" alt="${opts.hospitalName}" style="max-height:48px;max-width:160px;object-fit:contain;display:block;" />`
    : `<b style="font-size:16px;color:#111;">${opts.hospitalName}</b>`;
  await transporter.sendMail({
    from: `"${opts.hospitalName}" <${smtpUser}>`,
    to: opts.to,
    subject: `Invoice ${opts.billNo} - ${opts.hospitalName}`,
    html: `<table width="100%" cellpadding="0" cellspacing="0" style="font-family:Arial,sans-serif;max-width:480px;margin:0 auto;">
<tr><td style="padding:16px 24px;border-bottom:2px solid #e5e7eb;">
<table width="100%" cellpadding="0" cellspacing="0"><tr>
<td>${headerContent}</td>
<td align="right" style="font-size:12px;color:#6b7280;white-space:nowrap;">Invoice</td>
</tr></table>
</td></tr>
<tr><td style="padding:20px 24px;font-size:13px;color:#374151;line-height:1.6;">
Dear ${opts.patientName},<br><br>
Please find your invoice details below. The PDF is attached.
<table width="100%" cellpadding="0" cellspacing="0" style="margin:16px 0;border:1px solid #e5e7eb;border-radius:6px;font-size:13px;">
<tr><td style="padding:8px 12px;color:#6b7280;border-bottom:1px solid #f3f4f6;">Invoice</td><td style="padding:8px 12px;font-weight:600;color:#111;border-bottom:1px solid #f3f4f6;">${opts.billNo}</td></tr>
<tr><td style="padding:8px 12px;color:#6b7280;border-bottom:1px solid #f3f4f6;">Date</td><td style="padding:8px 12px;color:#111;border-bottom:1px solid #f3f4f6;">${opts.billDate}</td></tr>
<tr><td style="padding:8px 12px;color:#6b7280;border-bottom:1px solid #f3f4f6;">Patient ID</td><td style="padding:8px 12px;color:#111;border-bottom:1px solid #f3f4f6;">${opts.patientId}</td></tr>
<tr><td style="padding:8px 12px;color:#6b7280;border-bottom:1px solid #f3f4f6;">Total</td><td style="padding:8px 12px;font-weight:700;color:#111;border-bottom:1px solid #f3f4f6;">Rs. ${opts.total.toLocaleString("en-IN")}</td></tr>
<tr><td style="padding:8px 12px;color:#6b7280;border-bottom:1px solid #f3f4f6;">Paid</td><td style="padding:8px 12px;color:#059669;font-weight:600;border-bottom:1px solid #f3f4f6;">Rs. ${opts.paidAmount.toLocaleString("en-IN")}</td></tr>
<tr><td style="padding:8px 12px;color:#6b7280;">Status</td><td style="padding:8px 12px;font-weight:600;color:${isPaid ? "#059669" : "#d97706"};">${opts.status}</td></tr>
</table>
For queries, contact our billing department.
</td></tr>
<tr><td style="padding:12px 24px;font-size:11px;color:#9ca3af;border-top:1px solid #f3f4f6;">Auto-generated by ${opts.hospitalName}. Do not reply.</td></tr>
</table>`,
    attachments: [{ filename: `${opts.billNo}.pdf`, content: opts.pdfBuffer, contentType: "application/pdf" }],
  });
};
