-- AlterTable
ALTER TABLE `Appointment` ADD COLUMN `billingNote` TEXT NULL,
    ADD COLUMN `billingTransferred` BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE `Bill` ADD COLUMN `cgst` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `igst` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `isGst` BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN `sgst` DOUBLE NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `BillItem` ADD COLUMN `gstAmount` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `gstPercent` DOUBLE NOT NULL DEFAULT 0;
